/* daftar kabupaten atau kota-kota besar di Indonesia, berdasarkan kecocokan (data kabupaten atau kota) prakiraan cuaca BMKG dan (data kabupaten atau kota) di Wikipedia, terakhir update 12 September 2020 */

export const kabupatenKota = {
	Aceh: [
		'Kab. Aceh Barat',
		'Kab. Aceh Barat Daya',
		'Kab. Aceh Besar',
		'Kab. Aceh Jaya',
		'Kab. Aceh Selatan',
		'Kab. Aceh Singkil',
		'Kab. Aceh Tamiang',
		'Kab. Aceh Tengah',
		'Kab. Aceh Tenggara',
		'Kab. Aceh Timur',
		'Kab. Aceh Utara',
		'Kota Banda Aceh',
		'Kab. Bener Meriah',
		'Kab. Bireuen',
		'Kab. Gayo Lues',
		'Kota Langsa',
		'Kota Lhokseumawe',
		'Kab. Nagan Raya',
		'Kab. Pidie',
		'Kab. Pidie Jaya',
		'Kota Sabang',
		'Kab. Simeulue',
		'Kota Subulussalam'
	],

	Bali: [
		'Kab. Karangasem',
		'Kab. Bangli',
		'Kota Denpasar',
		'Kab. Gianyar',
		'Kab. Badung',
		'Kab. Jembrana',
		'Kab. Klungkung',
		'Kab. Buleleng',
		'Kab. Tabanan'
	],

	BangkaBelitung: [
		'Kab. Bangka Tengah [description: Koba]',
		'Kab. Belitung Timur',
		'Kab. Bangka Barat [description: Mentok]',
		'Kota Pangkalpinang',
		'Kab. Bangka',
		'Kab. Belitung [description: Tanjung Pandan]',
		'Kab. Bangka Selatan'
	],

	Banten: [
		'Kab. Serang [description: Ciruas]',
		'Kab. Pandeglang [description: Pandeglang]',
		'Kota Serang',
		'Kota Tangerang',
		'Kab. Tangerang'
	],

	Bengkulu: [
		'Kota Bengkulu',
		'Kab. Bengkulu Selatan',
		'Kab. Bengkulu Tengah',
		'Kab. Bengkulu Utara',
		'Kab. Kaur',
		'Kab. Kepahiang',
		'Kab. Lebong',
		'Kab. Muko Muko',
		'Kab. Rejang Lebong',
		'Kab. Seluma'
	],

	DIYogyakarta: [
		'Kab. Bantul',
		'Kab. Sleman',
		'Kab. Kulon Progo',
		'Kab. Gunung Kidul',
		'Kota Yogyakarta'
	],

	DKIJakarta: [
		'Kota Jakarta Barat',
		'Kota Jakarta Pusat',
		'Kota Jakarta Selatan',
		'Kota Jakarta Timur',
		'Kota Jakarta Utara',
		'Kab. Kepulauan Seribu'
	],

	Gorontalo: [
		'Kota Gorontalo',
		'Kab. Gorontalo Utara',
		'Kab. Gorontalo',
		'Kab. Pahuwato',
		'Kab. Bone Bolango',
		'Kab. Boalemo'
	],

	Jambi: [
		'Kab. Merangin',
		'Kab. Batanghari',
		'Kab. Bungo',
		'Kota Jambi',
		'Kab. Kerinci',
		'Kab. Tanjung Jabung Barat',
		'Kab. Tanjung Jabung Timur',
		'Kab. Muaro Jambi',
		'Kab. Sarolangun',
		'Kota Sungai Penuh',
		'Kab. Tebo'
	],

	JawaBarat: [
		'Kota Bandung',
		'Kota Banjar',
		'Kota Bekasi',
		'Kab. Ciamis',
		'Kab. Cianjur [description: Cianjur]',
		'Kab. Bogor [description: Cibinong]',
		'Kab. Bekasi',
		'Kota Cimahi',
		'Kota Cirebon',
		'Kota Depok',
		'Kab. Garut',
		'Kab. Indramayu',
		'Kab. Karawang',
		'Kota Bogor',
		'Kab. Kuningan',
		'Kab. Bandung Barat',
		'Kab. Majalengka',
		'Kab. Pangandaran',
		'Kab. Sukabumi [description: Pelabuhan Ratu]',
		'Kab. Purwakarta',
		'Kab. Tasikmalaya',
		'Kab. Bandung',
		'Kab. Subang',
		'Kab. Cirebon',
		'Kab. Sumedang',
		'Kota Tasikmalaya'
	],

	JawaTengah: [
		'Kab. Banjarnegara',
		'Kab. Batang',
		'Kab. Blora',
		'Kab. Boyolali',
		'Kab. Brebes',
		'Kab. Cilacap',
		'Kab. Demak',
		'Kab. Jepara',
		'Kab. Pekalongan',
		'Kab. Karanganyar',
		'Kab. Kebumen',
		'Kab. Kendal',
		'Kab. Klaten',
		'Kab. Kudus',
		'Kota Magelang',
		'Kab. Magelang',
		'Kab. Pati',
		'Kota Pekalongan',
		'Kab. Pemalang',
		'Kab. Purbalingga',
		'Kab. Grobogan',
		'Kab. Banyumas',
		'Kab. Purworejo',
		'Kab. Rembang',
		'Kota Salatiga',
		'Kota Semarang',
		'Kab. Tegal',
		'Kab. Sragen',
		'Kab. Sukoharjo',
		'Kota Surakarta',
		'Kota Tegal',
		'Kab. Temanggung',
		'Kab. Semarang',
		'Kab. Wonogiri',
		'Kab. Wonosobo'
	],

	JawaTimur: [
		'Kab. Bangkalan',
		'Kab. Banyuwangi',
		'Kota Batu',
		'Kab. Bojonegoro',
		'Kab. Bondowoso',
		'Kab. Gresik',
		'Kab. Jember',
		'Kab. Jombang',
		'Kab. Blitar',
		'Kab. Kediri',
		'Kab. Madiun',
		'Kab. Malang',
		'Kab. Mojokerto',
		'Kab. Pasuruan',
		'Kab. Probolinggo',
		'Kota Blitar',
		'Kota Kediri',
		'Kota Madiun',
		'Kota Malang',
		'Kota Mojokerto',
		'Kota Pasuruan',
		'Kota Probolinggo',
		'Kab. Lamongan',
		'Kab. Lumajang',
		'Kab. Magetan',
		'Kab. Nganjuk',
		'Kab. Ngawi',
		'Kab. Pacitan',
		'Kab. Pamekasan',
		'Kab. Ponorogo',
		'Kab. Sampang',
		'Kab. Sidoarjo',
		'Kab. Situbondo',
		'Kab. Sumenep',
		'Kota Surabaya',
		'Kab. Trenggalek',
		'Kab. Tuban',
		'Kab. Tulungagung'
	],

	KalimantanBarat: [
		'Kab. Bengkayang',
		'Kab. Kapuas Hulu',
		'Kab. Kayong Utara',
		'Kab. Ketapang',
		'Kab. Ngabang',
		'Kab. Melawi',
		'Kab. Mempawah [description: Mempawah]',
		'Kota Pontianak',
		'Kab. Sambas',
		'Kab. Sanggau',
		'Kab. Sekadau',
		'Kota Singkawang',
		'Kab. Sintang',
		'Kab. Kubu Raya [description: Sungai Raya]'
	],

	KalimantanSelatan: [
		'Kab. Hulu Sungai Utara',
		'Kota Banjarbaru',
		'Kota Banjarmasin',
		'Kab. Hulu Sungai Tengah',
		'Kab. Tanah Bambu',
		'Kab. Hulu Sungai Selatan',
		'Kab. Kotabaru',
		'Kab. Barito Kuala',
		'Kab. Banjar',
		'Kab. Balangan',
		'Kab. Tanah Laut',
		'Kab. Tapin',
		'Kab. Tabalong'
	],

	KalimantanTengah: [
		'Kab. Barito Selatan',
		'Kab. Katingan',
		'Kab. Kapuas',
		'Kab. Gunung Mas',
		'Kab. Seruyan',
		'Kab. Barito Utara',
		'Kab. Lamandau',
		'Kota Palangkaraya',
		'Kab. Kotawaringin Barat',
		'Kab. Pulang Pisau',
		'Kab. Murung Raya',
		'Kab. Kotawaringin Timur',
		'Kab. Sukamara',
		'Kab. Barito Timur'
	],

	KalimantanTimur: [
		'Kota Balikpapan',
		'Kota Bontang',
		'Kab. Penajam Paser Utara',
		'Kota Samarinda',
		'Kab. Kutai Barat',
		'Kab. Kutai Timur',
		'Kab. Paser',
		'Kab. Berau',
		'Kab. Kutai Kartanegara'
	],

	KalimantanUtara: [
		'Kab. Malinau',
		'Kab. Nunukan',
		'Kab. Tana Tidung',
		'Kab. Bulungan',
		'Kota Tarakan'
	],

	KepulauanRiau: [
		'Kota Batam',
		'Kab. Bintan',
		'Kab. Lingga',
		'Kab. Natuna',
		'Kab. Karimun',
		'Kota Tanjung Pinang',
		'Kab. Anambas'
	],

	Lampung: [
		'Kota Bandar Lampung',
		'Kab. Way Kanan',
		'Kab. Pesawaran',
		'Kab. Lampung Tengah',
		'Kab. Lampung Selatan',
		'Kab. Tanggamus',
		'Kab. Lampung Utara',
		'Kab. Lampung Barat [description: Liwa]',
		'Kab. Pesisir Barat [description: Krui]',
		'Kab. Tulang Bawang',
		'Kota Metro',
		'Kab. Tulang Bawang Barat',
		'Kab. Pringsewu',
		'Kab. Lampung Timur',
		'Kab. Mesuji'
	],

	Maluku: [
		'Kota Ambon',
		'Kab. Seram Bagian Timur',
		'Kab. Kepulauan Aru',
		'Kab. Maluku Barat Daya',
		'Kab. Buru Selatan',
		'Kab. Maluku Tengah',
		'Kab. Buru',
		'Kab. Seram Bagian Barat',
		'Kab. Maluku Tenggara Barat',
		'Kab. Maluku Tenggara'
	],

	MalukuUtara: [
		'Kab. Halmahera Barat',
		'Kab. Halmahera Selatan',
		'Kab. Halmahera Timur',
		'Kab. Pulau Morotai',
		'Kab. Kepulauan Sula',
		'Kab. Pulau Taliabu',
		'Kota Ternate',
		'Kota Tidore Kepulauan [description: Tidore]',
		'Kab. Halmahera Utara',
		'Kab. Halmahera Tengah'
	],

	NusaTenggaraBarat: [
		'Kab. Dompu',
		'Kab. Lombok Barat',
		'Kota Bima',
		'Kota Mataram',
		'Kab. Lombok Tengah',
		'Kab. Bima',
		'Kab. Lombok Timur',
		'Kab. Sumbawa',
		'Kab. Sumbawa Barat',
		'Kab. Lombok Utara'
	],

	NusaTenggaraTimur: [	
		'Kab. Belu',
		'Kab. Rote Ndao',
		'Kab. Ngada',
		'Kab. Malaka',
		'Kab. Manggarai Timur',
		'Kab. Ende',
		'Kab. Alor',
		'Kab. Timor Tengah Utara',
		'Kota Kupang',
		'Kab. Manggarai Barat',
		'Kab. Flores Timur',
		'Kab. Lembata',
		'Kab. Sikka',
		'Kab. Nagekeo',
		'Kab. Kupang',
		'Kab. Manggarai',
		'Kab. Sabu Raijua',
		'Kab. Timor Tengah Selatan',
		'Kab. Sumba Tengah',
		'Kab. Sumba Barat',
		'Kab. Sumba Timur',
		'Kab. Sumba Barat Daya'
	],

	Papua: [
		'Kab. Asmat',
		'Kab. Biak Numfor',
		'Kab. Waropen',
		'Kab. Mamberamo Raya',
		'Kab. Paniai',
		'Kota Jayapura',
		'Kab. Tolikara',
		'Kab. Mappi',
		'Kab. Merauke',
		'Kab. Puncak Jaya',
		'Kab. Nabire',
		'Kab. Pegunungan Bintang',
		'Kab. Sarmi',
		'Kab. Jayapura [description: Sentani]',
		'Kab. Kep Yapen',
		'Kab. Supiori',
		'Kab. Yahukimo',
		'Kab. Boven Digoel',
		'Kab. Mimika',
		'Kab. Jayawijaya',
		'Kab. Keerom'
	],

	PapuaBarat: [
		'Kab. Sorong',
		'Kab. Teluk Bintuni',
		'Kab. Fakfak',
		'Kab. Kaimana',
		'Kab. Maybrat',
		'Kab. Manokwari',
		'Kab. Manokwari Selatan',
		'Kota Sorong',
		'Kab. Sorong Selatan',
		'Kab. Raja Ampat',
		'Kab. Teluk Wondama'
	],

	Riau: [
		'Kab. Rokan Hilir',
		'Kab. Kampar',
		'Kab. Bengkalis',
		'Kota Dumai',
		'Kab. Pelalawan',
		'Kab. Rokan Hulu',
		'Kota Pekanbaru',
		'Kab. Indragiri Hulu',
		'Kab. Kepulauan Meranti',
		'Kab. Siak',
		'Kab. Kuantan Singingi',
		'Kab. Indragiri Hilir'
	],

	SulawesiBarat: [
		'Kab. Majene',
		'Kab. Mamasa',
		'Kab. Mamuju',
		'Kab. Mamuju Tengah',
		'Kab. Mamuju Utara',
		'Kab. Polewali Mandar'
	],

	SulawesiSelatan: [
		'Kab. Bantaeng',
		'Kab. Barru',
		'Kab. Kepulauan Selayar',
		'Kab. Bulukumba',
		'Kab. Enrekang',
		'Kab. Jeneponto',
		'Kab. Tana Toraja',
		'Kota Makasar',
		'Kab. Luwu Timur',
		'Kab. Maros',
		'Kab. Luwu Utara',
		'Kota Palopo',
		'Kab. Pangkajene dan Kepulauan',
		'Kota Pare Pare',
		'Kab. Pinrang',
		'Kab. Toraja Utara',
		'Kab. Wajo',
		'Kab. Sidenreng Rappang',
		'Kab. Sinjai',
		'Kab. Gowa',
		'Kab. Takalar',
		'Kab. Bone',
		'Kab. Soppeng'
	],

	SulawesiTengah: [
		'Kab. Tojo Una-Una',
		'Kab. Morowali',
		'Kab. Buol',
		'Kab. Donggala',
		'Kab. Banggai',
		'Kota Palu',
		'Kab. Parigi Moutong',
		'Kab. Poso',
		'Kab. Banggai Kepulauan',
		'Kab. Sigi Biromaru',
		'Kab. Toli-Toli'
	],

	SulawesiTenggara: [
		'Kota Bau - Bau',
		'Kab. Bombana',
		'Kab. Buton Utara',
		'Kab. Buton',
		'Kab. Kolaka',
		'Kab. Kolaka Utara',
		'Kab. Konawe',
		'Kab. Konawe Selatan',
		'Kota Kendari',
		'Kab. Muna',
		'Kab. Konawe Utara',
		'Kab. Wakatobi'
	],

	SulawesiUtara: [
		'Kab. Minahasa Utara',
		'Kab. Minahasa Selatan',
		'Kota Bitung',
		'Kab. Bolaang Mongondow Utara [description: Boroko]',
		'Kota Kotamobagu',
		'Kab. Bolaang Mongondow [description: Lolak]',
		'Kota Manado',
		'Kab. Talaud',
		'Kab. Sitaro',
		'Kab. Minahasa Tenggara',
		'Kab. Sangihe',
		'Kota Tomohon',
		'Kab. Minahasa'
	],

	SumateraBarat: [
		'Kab. Solok',
		'Kab. Tanah Datar',
		'Kota Bukittinggi',
		'Kab. Agam',
		'Kab. Pasaman',
		'Kab. Sijunjung',
		'Kota Padang',
		'Kab. Solok Selatan',
		'Kota Padangpanjang',
		'Kab. Pesisir Selatan',
		'Kota Pariaman',
		'Kab. Padang Pariaman',
		'Kota Payakumbuh',
		'Kab. Dharmasraya',
		'Kab. Limapuluh Kota',
		'Kota Sawahlunto',
		'Kab. Pasaman Barat',
		'Kota Solok',
		'Kab. Kepulauan Mentawai'
	],

	SumateraSelatan: [
		'Kab. Ogan Komering Ulu',
		'Kab. Ogan Ilir',
		'Kab. Ogan Komering Ilir',
		'Kab. Lahat',
		'Kota Lubuk Linggau',
		'Kab. Ogan Komering Ulu Timur',
		'Kab. Ogan Komering Ulu Selatan',
		'Kab. Muaraenim',
		'Kab. Musi Rawas Utara',
		'Kab. Musi Rawas',
		'Kota Pagar Alam',
		'Kota Palembang',
		'Kab. Banyuasin',
		'Kota Prabumulih',
		'Kab. Musi Banyuasin',
		'Kab. Penukal Abab Lematang Ilir',
		'Kab. Empat Lawang'
	],

	SumateraUtara: [
		'Kab. Labuhanbatu Utara',
		'Kab. Toba Samosir',
		'Kota Binjai',
		'Kab. Humbang Hasundutan',
		'Kab. Nias',
		'Kab. Padanglawas Utara [description: Gunung Tua]',
		'Kab. Karo',
		'Kab. Asahan',
		'Kab. Labuhanbatu Selatan',
		'Kab. Nias Barat',
		'Kab. Batubara',
		'Kab. Nias Utara',
		'Kab. Deli Serdang',
		'Kota Medan',
		'Kota Padang Sidempuan',
		'Kab. Tapanuli Tengah',
		'Kab. Samosir',
		'Kab. Mandailing Natal',
		'Kab. Simalungun',
		'Kota Pematang Siantar',
		'Kab. Labuhanbatu',
		'Kab. Pak-Pak Bharat',
		'Kab. Serdang Bedagai',
		'Kota Sibolga',
		'Kab. Padanglawas',
		'Kab. Dairi',
		'Kab. Tapanuli Selatan [description: Sipirok]',
		'Kab. Langkat',
		'Kota Tanjung Balai',
		'Kab. Tapanuli Utara',
		'Kota Tebing Tinggi',
		'Kab. Nias Selatan'
	]
}